### ISSUE TITLE
latest NUT and winnut-client errors

### ISSUE THREAD

**Issue by ms8x8x** [gitmachtl/various#4]
1. latest NUT, with log error  ">>> TLS requested, but not supported"
2. latest winnut-client, will hang when connecting, with repeated logs:

Tue 18 Jul 2023 11:13:03 AM CST REM_IP=192.168.0.106    PID=154230      GET VAR qnapups ups.mfr
 for UPSNAME=qnapups3:03 AM CST REM_IP=192.168.0.106    PID=154230      >>> Requested VAR=ups.mfr

**Comment by gitmachtl** [comment]
1. TLS is not supported via this wrapper script, but that should not stop a NUT client to work in "non-TLS" mode
2. Thats interesting, never saw a request for ups.mfr until now. There should be another output in the log below like
 `>>> failed to process variable ups.mfr (UPS_ups_mfr)`
 correct?

For a test, please open the upsnutwrapper.sh file in an editor and search for the entry:
`UPS_device_mfr="UPS NUT Apcupsd Wrapper"`

Insert/Add a new variable below that entry like:
`UPS_ups_mfr="UPS NUT Apcupsd Wrapper"`

Save it and check the logs again. Please let me know if this has solved your issue.

**Comment by gitmachtl** [comment]
@ms8x8x upswrapper script has been updated to version 1.9 and it supports more values now.
